// Dev-time tool: decimate a dense OBJ to a low-poly mesh the in-app renderer can handle.
// Vertex clustering — snap verts to a coarse grid, merge to the cell average, rebuild faces.
// Keeps the OBJ's face winding (so computed normals stay outward). Writes male-mesh.js.
//   node decimate.mjs <gridN>   (gridN = cells along the longest axis; higher = more faces)
import { readFileSync, writeFileSync } from "node:fs";

const N = parseInt(process.argv[2] || "48", 10);
const SRC = "/home/maganra/Downloads/Male.OBJ";
const lines = readFileSync(SRC, "utf8").split("\n");

const verts = [], faces = [];
for (const line of lines) {
  if (line[0] === "v" && line[1] === " ") {
    const p = line.split(/\s+/); verts.push([+p[1], +p[2], +p[3]]);
  } else if (line[0] === "f" && line[1] === " ") {
    const p = line.trim().split(/\s+/), idx = [];
    for (let i = 1; i < p.length; i++) idx.push(parseInt(p[i].split("/")[0], 10) - 1);
    faces.push(idx);
  }
}

const mn = [Infinity, Infinity, Infinity], mx = [-Infinity, -Infinity, -Infinity];
for (const v of verts) for (let k = 0; k < 3; k++) { if (v[k] < mn[k]) mn[k] = v[k]; if (v[k] > mx[k]) mx[k] = v[k]; }
const ext = Math.max(mx[0] - mn[0], mx[1] - mn[1], mx[2] - mn[2]);
const cell = ext / N;

const cellMap = new Map();
const sum = [], cnt = [];
const vToCell = new Int32Array(verts.length);
for (let i = 0; i < verts.length; i++) {
  const v = verts[i];
  const key = Math.floor((v[0] - mn[0]) / cell) + "," + Math.floor((v[1] - mn[1]) / cell) + "," + Math.floor((v[2] - mn[2]) / cell);
  let id = cellMap.get(key);
  if (id === undefined) { id = cnt.length; cellMap.set(key, id); sum.push([0, 0, 0]); cnt.push(0); }
  sum[id][0] += v[0]; sum[id][1] += v[1]; sum[id][2] += v[2]; cnt[id]++;
  vToCell[i] = id;
}
const newVerts = sum.map((s, id) => [s[0] / cnt[id], s[1] / cnt[id], s[2] / cnt[id]]);

const newFaces = [], seen = new Set();
for (const f of faces) {
  const m = [];
  for (const vi of f) { const c = vToCell[vi]; if (m.length === 0 || m[m.length - 1] !== c) m.push(c); }
  if (m.length > 1 && m[0] === m[m.length - 1]) m.pop();
  if (m.length < 3) continue;
  const key = [...m].sort((a, b) => a - b).join(",");
  if (seen.has(key)) continue; seen.add(key);
  newFaces.push(m);
}

const rv = newVerts.map((v) => v.map((x) => +x.toFixed(3)));
writeFileSync("male-mesh.js",
  "// Auto-generated by decimate.mjs from Male.OBJ — do not hand-edit.\n" +
  "export const MALE_VERTS=" + JSON.stringify(rv) + ";\n" +
  "export const MALE_FACES=" + JSON.stringify(newFaces) + ";\n");
console.log("N=" + N, "verts:", rv.length, "faces:", newFaces.length, "(from", verts.length, "v /", faces.length, "f), bbox ext", ext.toFixed(3));
